
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 120
#define YY_END_OF_BUFFER 121
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[680] =
    {   0,
        0,    0,    0,    0,  121,  119,  116,  115,  119,  119,
      119,  119,  113,    4,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,    2,  119,  116,  119,  119,  113,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      116,  115,    0,  114,    0,    0,  113,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   90,    0,    0,    3,    0,
        2,    2,    0,  116,    0,  113,    0,    0,    0,    0,
        0,    0,    0,    0,    2,    0,    0,  118,    0,  118,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   75,    0,
        0,    0,   70,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   68,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  117,    0,    0,    0,    0,    0,
       18,    0,    0,    0,    0,    0,   42,    0,    0,    0,

        6,    0,    0,   44,    0,    0,    0,    0,   35,    0,
        0,    0,   38,   34,    0,    0,    0,   17,    0,    0,
      112,    0,    0,    0,    0,    0,    0,    0,    0,   96,
        0,    0,    0,    0,    0,    0,   91,   94,   53,    0,
        0,    0,    0,    0,    0,   63,    0,    0,    0,    0,
        0,    0,   97,    0,    0,    0,    0,    0,    0,   57,
        0,    0,    0,    0,    0,   47,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   93,    0,    0,
        0,   55,   12,    0,    0,    0,    0,    0,   26,    0,
        0,    0,    0,    0,    0,   10,    0,    0,    0,    0,

        8,    0,    0,    0,    7,    0,    0,    0,    0,    0,
        0,    0,   28,    0,    0,    0,   61,   89,    0,    0,
       83,    0,    0,    0,    0,   77,    0,    0,    0,    0,
        0,   92,    0,    0,    0,    0,  111,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   52,    0,
        0,  103,    0,    0,   60,    0,    0,   67,    0,    0,
        0,    0,   54,    0,    0,    0,   71,    0,    0,   32,
       45,    0,    0,    0,    0,    0,    0,    0,   27,    0,
        0,    0,    0,    0,   13,    0,   29,    0,   22,    0,
        0,    0,    0,   82,    0,   69,   51,   65,   48,    0,

        0,  101,    0,   72,    0,    0,    0,    0,    0,   49,
        0,    0,    0,    0,    0,    0,   50,  107,    0,    0,
        0,   58,    0,   56,   62,    0,   98,    0,   88,  110,
        0,    0,    1,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    5,   16,    0,    0,    0,    0,   39,    0,
       21,    0,   99,    0,    0,   95,    0,    0,    0,   81,
        0,    0,    0,    0,   59,   76,   74,    0,    0,    0,
        0,   87,    0,    0,    0,    0,   41,    0,    0,   33,
       11,    9,   20,    0,    0,   14,    0,    0,    0,    0,
        0,    0,  108,    0,    0,    0,    0,    0,    0,    0,

        0,   86,    0,    0,  104,   80,    0,  100,   73,   15,
        0,   43,    0,    0,    0,    0,    0,    0,    0,    0,
       78,  102,   64,    0,  106,   46,   84,   85,    0,    0,
        0,   19,    0,    0,    0,    0,    0,    0,    0,    0,
       66,    0,  105,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   36,   37,    0,    0,    0,    0,
        0,    0,   79,  109,    0,    0,    0,   25,   31,    0,
        0,    0,   23,    0,    0,   24,   30,   40,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    8,    1,    9,    1,
        1,    1,   10,    1,   11,   12,    1,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,    1,    1,
        1,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
        1,   31,   32,   33,   34,   35,   36,    1,   37,   38,
       39,   40,   41,    1,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   58,    1,   59,   60,   61,   62,   63,   64,    1,
       65,    1,   12,   12,   12,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    2,    3,    2,    2,    1,    2,    1,    1,    2,
        2,    2,    2,    1,    2,    2,    2,    1,    1,    2,
        1,    2,    2,    1,    2,    2,    1,    1,    1,    2,
        1,    2,    2,    1,    1,    2,    1,    2,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    1
    } ;

static const flex_int16_t yy_base[685] =
    {   0,
        0,   59,   84,   63,  843,  844,   66,  844,  839,  835,
      800,  826,  825,  844,  811,  805,   45,   44,  807,   43,
       63,  806,   61,   64,   69,  817,  803,   96,   79,   99,
      816,   72,   67,   75,   88,   66,   90,   93,   62,   96,
       98,  102,  110,  104,  113,  120,  110,  115,  783,  826,
      147,  844,  825,  177,  181,  184,  187,  190,  199,  202,
      799,  185,  190,  198,  186,  199,  207,  219,  213,  258,
       76,  844,  820,  844,  816,  815,  810,  789,  806,  805,
      144,  790,  803,  796,  801,  781,  785,  787,  789,  793,
      775,  771,  776,  779,  779,  168,  781,  194,  776,  782,

      773,  773,  785,  783,  772,  782,  770,  232,  231,  148,
      751,  740,  750,  745,  730,  733,  730,  732,  744,  729,
      118,  726,  720,  723,  722,  732,  726,  725,  192,  718,
      713,  192,  715,  730,  195,  715,  717,  710,  246,  203,
      719,  723,  726,  725,  711,  717,  716,  708,  704,  197,
      700,  704,  702,  697,  231,  844,  698,  754,  844,  228,
      844,  844,  753,  295,  264,  282,  277,  294,  246,  297,
      296,  299,  314,  308,  844,  752,    0,  844,  745,  744,
      737,  723,  722,  716,  717,  716,  710,  714,  723,  715,
      715,  723,  707,  721,  719,  718,  704,  703,  715,  718,

      690,  312,  705,  697,  711,  705,  700,  701,  702,  693,
      704,  692,  695,  267,  671,  676,  661,  670,  663,  655,
      653,  660,  656,  650,  653,  649,  654,  646,  646,  649,
      643,  642,  643,  641,  646,  651,  652,  636,  844,  635,
      645,  635,  844,  640,  645,  634,  646,  636,  628,  626,
      632,  628,  629,  268,  622,  635,  619,  629,  632,  622,
      632,  631,  629,  623,  623,  627,  628,  611,  618,  607,
      610,  844,  619,  603,  613,  612,  601,  335,  318,  313,
      634,  323,  326,  324,  844,  629,  642,  641,  642,  633,
      844,  639,  639,  621,  619,  632,  844,  608,  630,  622,

      611,  631,  612,  844,  614,  180,  626,  616,  844,  626,
      611,  610,  844,  844,  607,  608,  606,  844,  612,  315,
      844,  578,  574,  573,  584,  583,  569,  571,  580,  844,
      579,  565,  577,  572,  579,  574,  844,  844,  844,  577,
      572,  571,  606,  568,  564,  844,  567,  566,  565,  568,
      554,  557,  844,  547,  548,  555,  548,  561,  546,  844,
      552,  547,  541,  538,  553,  844,  550,  549,  538,  537,
      532,  531,  527,  529,  533,  538,  534,  844,  527,  531,
      523,  844,  844,  580,  329,  567,  332,  342,  844,  559,
      561,  556,  560,  546,  541,  844,  560,  541,  546,  541,

      844,  556,  549,  550,  844,  545,  552,  533,  550,  538,
      536,  534,  844,  532,  531,  539,  844,  844,  511,  499,
      844,  509,  500,  498,  494,  844,  506,  502,  499,  503,
      485,  844,  501,  223,  492,  491,  844,  495,  497,  481,
      481,  493,  492,  495,  488,  477,  477,  491,  844,  486,
      481,  844,  470,  482,  844,  474,  472,  844,  465,  472,
      465,  477,  844,  458,  462,  467,  844,  490,  337,  844,
      844,  491,  489,  494,  493,  492,  483,  498,  844,  486,
      492,  479,  488,  476,  844,  486,  844,  464,  844,  478,
      473,  466,  459,  844,  455,  844,  844,  844,  844,  444,

      443,  844,  451,  844,  450,  445,  438,  447,  442,  844,
      430,  430,  445,  430,  434,  431,  844,  844,  432,  427,
      437,  844,  421,  844,  844,  427,  844,  430,  844,  844,
      433,  432,  844,  340,  459,  446,  458,  447,  446,  436,
      442,  446,  844,  844,  449,  437,  436,  351,  844,  434,
      844,  412,  844,  418,  417,  844,  415,  413,  404,  844,
      403,  400,  411,  396,  844,  844,  844,  405,  398,  408,
      399,  844,  403,  405,  404,  418,  844,  427,  426,  844,
      844,  844,  844,  431,  409,  844,  415,  414,  426,  415,
      421,  397,  844,  392,  391,  375,  385,  375,  377,  385,

      372,  844,  381,  370,  844,  844,  378,  844,  844,  844,
      408,  844,  410,  410,  393,  395,  398,  406,  399,  388,
      844,  844,  844,  357,  844,  844,  844,  844,  361,  355,
      354,  844,  388,  387,  381,  379,  391,  392,  385,  388,
      844,  359,  844,  358,  385,  377,  379,  368,  383,  380,
      369,  376,  350,  349,  844,  844,  361,  357,  342,  342,
      345,  349,  844,  844,  341,  336,  271,  844,  844,  258,
      228,  217,  844,  129,   76,  844,  844,  844,  844,  382,
      385,  387,  389,  392
    } ;

static const flex_int16_t yy_def[685] =
    {   0,
      679,    1,    1,    3,  679,  679,  679,  679,  679,  680,
      681,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  682,
      679,  679,  679,  683,  683,  683,  683,  683,  683,  683,
      679,   60,   60,   60,   60,   60,   60,   60,   60,  682,
      679,  679,  680,  679,  679,  684,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,

      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  682,  679,  679,
      679,  679,  679,   60,   60,   60,   60,   60,  679,   60,
       60,   60,   60,   60,  679,  682,   70,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,

      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,   60,   60,
      679,   60,   60,   60,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,

      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,   60,  679,   60,   60,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,

      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,   60,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,

      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,   60,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,

      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,    0,  679,
      679,  679,  679,  679
    } ;

static const flex_int16_t yy_nxt[910] =
    {   0,
        6,    7,    8,    9,    7,   10,    6,    6,   11,   12,
       12,    6,   13,   14,   15,   16,   17,   18,   19,   20,
       21,    6,   22,    6,    6,   23,   24,   25,   26,   27,
       28,   29,   30,    6,    6,   31,    6,    6,   32,    6,
        6,    6,   33,   34,   35,   36,   37,   38,    6,   39,
        6,    6,    6,   40,   41,   42,   43,   44,   45,   46,
       47,   48,    6,   49,    6,   50,   80,   71,   85,   70,
       71,   86,   82,   81,   83,   90,  108,   71,   92,   91,
       71,   87,   93,   95,  109,   51,   52,   53,   54,   51,
       55,   88,   94,   56,   56,   55,   57,   96,   58,   59,

       60,  102,   61,   62,  129,   55,   63,  678,   55,   64,
       99,  103,  104,   65,  100,   66,   67,  105,  130,   68,
      110,   55,  123,   55,  101,  111,  112,  124,  114,  106,
      113,  115,  125,  116,  118,  127,  117,  119,  131,  135,
      136,  120,  132,  128,  121,  126,  133,   69,  138,  122,
      143,  140,  134,  141,  137,  145,  677,  144,  139,  146,
      227,  160,  148,  147,  149,   93,  153,  142,  154,  150,
      155,  184,  156,  228,  185,   94,  151,  152,   71,  162,
      163,  164,  679,  162,  163,  679,  162,  163,  679,  162,
      163,  679,  162,  163,  200,  201,  166,  406,  215,  166,

      679,  162,  163,  679,  162,  163,  165,  165,  216,  407,
      170,  165,  171,   86,   98,  167,   91,   89,  679,  165,
      165,  172,  203,  168,  204,  105,  679,  679,  165,   79,
       81,  173,  104,  174,  165,  679,  108,  106,  214,  240,
      165,  679,  245,  109,  109,  236,  257,  679,  676,  246,
      237,  247,  241,  268,  242,  269,  258,  278,  675,  157,
      175,  176,  177,  281,  177,  196,  188,  177,  177,  177,
      177,  320,  177,  177,  177,  274,  505,  177,  275,  177,
      177,  506,  177,  177,  276,  165,  674,  177,  251,  177,
      177,  252,  679,  177,  166,  177,   71,  177,  165,  164,

      253,  254,  673,  165,  255,  679,  256,  321,  280,  279,
      679,  282,  359,  194,  360,  165,  165,  165,  165,  320,
      165,  177,  679,  679,  679,  679,  208,  679,  283,  165,
      307,  308,  385,  284,  165,  165,  679,  383,  384,  165,
      288,  679,  679,  294,  165,  165,  679,  165,  387,  388,
      165,  679,  679,  165,  679,  321,  534,  679,  165,  389,
      679,  165,  413,  165,  469,  679,  672,  587,  679,  671,
      679,  670,  669,  668,  667,  666,  551,  588,  665,  589,
      590,  591,   73,   73,   73,   75,   75,  158,  158,  158,
      165,  165,  179,  179,  664,  663,  662,  661,  660,  659,

      658,  657,  656,  655,  654,  653,  652,  651,  650,  649,
      648,  647,  646,  645,  644,  643,  642,  641,  640,  639,
      638,  637,  636,  635,  634,  633,  632,  631,  630,  629,
      628,  627,  626,  625,  624,  623,  622,  621,  620,  619,
      618,  617,  616,  615,  614,  613,  612,  611,  610,  609,
      608,  607,  606,  605,  604,  603,  602,  601,  600,  599,
      598,  597,  596,  595,  594,  593,  592,  586,  585,  584,
      583,  582,  581,  580,  579,  578,  577,  576,  575,  574,
      573,  572,  571,  570,  569,  568,  567,  566,  565,  564,
      563,  562,  561,  560,  559,  558,  557,  556,  555,  554,

      553,  552,  551,  550,  549,  548,  547,  546,  545,  544,
      543,  542,  541,  540,  539,  538,  537,  536,  535,  533,
      532,  531,  530,  529,  528,  527,  526,  525,  524,  523,
      522,  521,  520,  519,  518,  517,  516,  515,  514,  513,
      512,  511,  510,  509,  508,  507,  504,  503,  502,  501,
      500,  499,  498,  497,  496,  495,  494,  493,  492,  491,
      490,  489,  488,  487,  486,  485,  484,  483,  482,  481,
      480,  479,  478,  477,  476,  475,  474,  473,  472,  471,
      470,  468,  383,  467,  466,  465,  464,  463,  462,  461,
      460,  459,  458,  457,  456,  455,  454,  453,  452,  451,

      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  439,  438,  437,  436,  435,  434,  433,  432,  431,
      430,  429,  428,  427,  426,  425,  424,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  414,  413,  412,  411,
      410,  409,  408,  405,  404,  403,  402,  401,  400,  399,
      398,  397,  396,  395,  394,  393,  392,  391,  390,  389,
      386,  382,  381,  380,  379,  378,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  368,  367,  366,  365,  364,
      363,  362,  361,  358,  357,  356,  355,  354,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  344,  343,  342,

      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  285,  175,  162,  159,  277,  273,  272,
      271,  270,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  250,  249,  248,  244,  243,  239,  238,  235,  234,
      233,  232,  231,  230,  229,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  213,  212,  211,  210,  209,

      208,  207,  206,  205,  202,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  183,
      182,  181,   77,  180,  178,   74,  169,  161,  159,  157,
      107,   98,   97,   89,   84,   79,   78,   77,   77,   76,
       74,   72,  679,    5,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,

      679,  679,  679,  679,  679,  679,  679,  679,  679
    } ;

static const flex_int16_t yy_chk[910] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,   17,    7,   20,    4,
        7,   20,   18,   17,   18,   23,   32,   71,   24,   23,
       71,   21,   24,   25,   32,    2,    3,    3,    3,    4,
        3,   21,   24,    3,    3,    3,    3,   25,    3,    3,

        3,   29,    3,    3,   39,    3,    3,  675,    3,    3,
       28,   29,   29,    3,   28,    3,    3,   30,   39,    3,
       33,    3,   36,    3,   28,   33,   33,   36,   34,   30,
       33,   34,   37,   34,   35,   38,   34,   35,   40,   41,
       41,   35,   40,   38,   35,   37,   40,    3,   42,   35,
       44,   43,   40,   43,   41,   45,  674,   44,   42,   45,
      121,   51,   46,   45,   46,   51,   47,   43,   47,   46,
       48,   81,   48,  121,   81,   51,   46,   46,   54,   54,
       54,   54,   55,   55,   55,   56,   56,   56,   57,   57,
       57,   58,   58,   58,   96,   96,   56,  306,  110,   57,

       59,   59,   59,   60,   60,   60,   62,   65,  110,  306,
       62,   63,   64,   62,   65,   58,   64,   63,   63,   64,
       66,   66,   98,   60,   98,   67,   64,   66,   67,   59,
       60,   66,   66,   68,   69,   67,  108,   67,  109,  132,
       68,   69,  135,  109,  108,  129,  140,   68,  672,  135,
      129,  135,  132,  150,  132,  150,  140,  160,  671,   69,
       70,   70,   70,  169,   70,  160,  169,   70,   70,   70,
       70,  214,   70,   70,   70,  155,  434,   70,  155,   70,
       70,  434,   70,   70,  155,  165,  670,   70,  139,   70,
       70,  139,  165,   70,  166,   70,  164,   70,  167,  164,

      139,  139,  667,  166,  139,  167,  139,  214,  168,  167,
      166,  170,  254,  171,  254,  168,  164,  171,  170,  320,
      172,   70,  168,  164,  171,  170,  172,  172,  173,  174,
      202,  202,  279,  174,  280,  173,  174,  278,  278,  279,
      280,  280,  173,  282,  282,  284,  279,  283,  283,  284,
      385,  282,  284,  387,  283,  320,  469,  385,  469,  385,
      387,  534,  387,  388,  388,  469,  666,  548,  534,  665,
      388,  662,  661,  660,  659,  658,  534,  548,  657,  548,
      548,  548,  680,  680,  680,  681,  681,  682,  682,  682,
      683,  683,  684,  684,  654,  653,  652,  651,  650,  649,

      648,  647,  646,  645,  644,  642,  640,  639,  638,  637,
      636,  635,  634,  633,  631,  630,  629,  624,  620,  619,
      618,  617,  616,  615,  614,  613,  611,  607,  604,  603,
      601,  600,  599,  598,  597,  596,  595,  594,  592,  591,
      590,  589,  588,  587,  585,  584,  579,  578,  576,  575,
      574,  573,  571,  570,  569,  568,  564,  563,  562,  561,
      559,  558,  557,  555,  554,  552,  550,  547,  546,  545,
      542,  541,  540,  539,  538,  537,  536,  535,  532,  531,
      528,  526,  523,  521,  520,  519,  516,  515,  514,  513,
      512,  511,  509,  508,  507,  506,  505,  503,  501,  500,

      495,  493,  492,  491,  490,  488,  486,  484,  483,  482,
      481,  480,  478,  477,  476,  475,  474,  473,  472,  468,
      466,  465,  464,  462,  461,  460,  459,  457,  456,  454,
      453,  451,  450,  448,  447,  446,  445,  444,  443,  442,
      441,  440,  439,  438,  436,  435,  433,  431,  430,  429,
      428,  427,  425,  424,  423,  422,  420,  419,  416,  415,
      414,  412,  411,  410,  409,  408,  407,  406,  404,  403,
      402,  400,  399,  398,  397,  395,  394,  393,  392,  391,
      390,  386,  384,  381,  380,  379,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  368,  367,  365,  364,  363,

      362,  361,  359,  358,  357,  356,  355,  354,  352,  351,
      350,  349,  348,  347,  345,  344,  343,  342,  341,  340,
      336,  335,  334,  333,  332,  331,  329,  328,  327,  326,
      325,  324,  323,  322,  319,  317,  316,  315,  312,  311,
      310,  308,  307,  305,  303,  302,  301,  300,  299,  298,
      296,  295,  294,  293,  292,  290,  289,  288,  287,  286,
      281,  277,  276,  275,  274,  273,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  242,  241,  240,  238,  237,  236,  235,

      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  216,  215,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  201,  200,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  176,  163,  158,  157,  154,  153,
      152,  151,  149,  148,  147,  146,  145,  144,  143,  142,
      141,  138,  137,  136,  134,  133,  131,  130,  128,  127,
      126,  125,  124,  123,  122,  120,  119,  118,  117,  116,
      115,  114,  113,  112,  111,  107,  106,  105,  104,  103,

      102,  101,  100,   99,   97,   95,   94,   93,   92,   91,
       90,   89,   88,   87,   86,   85,   84,   83,   82,   80,
       79,   78,   77,   76,   75,   73,   61,   53,   50,   49,
       31,   27,   26,   22,   19,   16,   15,   13,   12,   11,
       10,    9,    5,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,
      679,  679,  679,  679,  679,  679,  679,  679,  679,  679,

      679,  679,  679,  679,  679,  679,  679,  679,  679
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lev_comp.l"
#line 2 "lev_comp.l"
/*	SCCS Id: @(#)lev_lex.c	3.4	2002/03/27	*/
/*	Copyright (c) 1989 by Jean-Christophe Collet */
/* NetHack may be freely redistributed.  See license for details. */

#define LEV_LEX_C

#include "hack.h"
#include "lev_comp.h"
#include "sp_lev.h"

/* Most of these don't exist in flex, yywrap is macro and
 * yyunput is properly declared in flex.skel.
 */
#if !defined(FLEX_SCANNER) && !defined(FLEXHACK_SCANNER)
int FDECL(yyback, (int *,int));
int NDECL(yylook);
int NDECL(yyinput);
int NDECL(yywrap);
int NDECL(yylex);
	/* Traditional lexes let yyunput() and yyoutput() default to int;
	 * newer ones may declare them as void since they don't return
	 * values.  For even more fun, the lex supplied as part of the
	 * newer unbundled compiler for SunOS 4.x adds the void declarations
	 * (under __STDC__ or _cplusplus ifdefs -- otherwise they remain
	 * int) while the bundled lex and the one with the older unbundled
	 * compiler do not.  To detect this, we need help from outside --
	 * sys/unix/Makefile.utl.
	 *
	 * Digital UNIX is difficult and still has int in spite of all
	 * other signs.
	 */
# if defined(NeXT) || defined(SVR4) || defined(_AIX32)
#  define VOIDYYPUT
# endif
# if !defined(VOIDYYPUT) && defined(POSIX_TYPES)
#  if !defined(BOS) && !defined(HISX) && !defined(_M_UNIX) && !defined(VMS)
#   define VOIDYYPUT
#  endif
# endif
# if !defined(VOIDYYPUT) && defined(WEIRD_LEX)
#  if defined(SUNOS4) && defined(__STDC__) && (WEIRD_LEX > 1)
#   define VOIDYYPUT
#  endif
# endif
# if defined(VOIDYYPUT) && defined(__osf__)
#  undef VOIDYYPUT
# endif
# ifdef VOIDYYPUT
void FDECL(yyunput, (int));
void FDECL(yyoutput, (int));
# else
int FDECL(yyunput, (int));
int FDECL(yyoutput, (int));
# endif
#endif	/* !FLEX_SCANNER && !FLEXHACK_SCANNER */

#ifdef FLEX_SCANNER
#define YY_MALLOC_DECL \
	      genericptr_t FDECL(malloc, (size_t)); \
	      genericptr_t FDECL(realloc, (genericptr_t,size_t));
#endif

void FDECL(init_yyin, (FILE *));
void FDECL(init_yyout, (FILE *));

/*
 * This doesn't always get put in lev_comp.h
 * (esp. when using older versions of bison).
 */
extern YYSTYPE yylval;

int line_number = 1, colon_line_number = 1;
static char map[4096];
static int map_cnt = 0;

/*
 *	This is a hack required by Michael Hamel to get things
 *	working on the Mac.
 */
#if defined(MAC_MPW) && !defined(FLEX_SCANNER) && !defined(FLEXHACK_SCANNER)
#undef input
#undef unput
#define unput(c) { yytchar = (c); if (yytchar == 10) yylineno--; *yysptr++ = yytchar; }
# ifndef YYNEWLINE
# define YYNEWLINE 10
# endif

char
input()		/* Under MPW \n is chr(13)! Compensate for this. */
{
	if (yysptr > yysbuf) return(*--yysptr);
	else {
		yytchar = getc(yyin);
		if (yytchar == '\n') {
		    yylineno++;
		    return(YYNEWLINE);
		}
		if (yytchar == EOF) return(0);
		else		    return(yytchar);
	}
}
#endif	/* MAC_MPW && !FLEX_SCANNER && !FLEXHACK_SCANNER */

#line 969 "lex.yy.c"

#line 971 "lex.yy.c"

#define INITIAL 0
#define MAPC 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 110 "lev_comp.l"

#line 1194 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 680 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 844 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 111 "lev_comp.l"
{
		  BEGIN(INITIAL);
		  yylval.map = (char *) alloc(map_cnt + 1);
		  (void) strncpy(yylval.map, map, map_cnt);
		  yylval.map[map_cnt] = 0;
		  map_cnt = 0;
		  return MAP_ID;
		}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 119 "lev_comp.l"
{
		  int len = yyleng;
		  /* convert \r\n to \n */
		  if (len >= 2 && yytext[len - 2] == '\r') len -= 1;
		  line_number++;
		  (void) strncpy(map + map_cnt, yytext, len);
		  map_cnt += len;
		  map[map_cnt - 1] = '\n';
		  map[map_cnt] = '\0';
		}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 129 "lev_comp.l"
{ line_number++; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 130 "lev_comp.l"
{ colon_line_number = line_number; return ':'; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 131 "lev_comp.l"
return MESSAGE_ID;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 132 "lev_comp.l"
return MAZE_ID;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 133 "lev_comp.l"
return NOMAP_ID;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 134 "lev_comp.l"
return LEVEL_ID;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 135 "lev_comp.l"
return LEV_INIT_ID;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 136 "lev_comp.l"
return FLAGS_ID;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 137 "lev_comp.l"
return GEOMETRY_ID;
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 138 "lev_comp.l"
{ BEGIN(MAPC); line_number++; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 139 "lev_comp.l"
return OBJECT_ID;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 140 "lev_comp.l"
return OBJFLAGS_ID;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 141 "lev_comp.l"
return COBJECT_ID;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 142 "lev_comp.l"
return MONSTER_ID;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 143 "lev_comp.l"
return TRAP_ID;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 144 "lev_comp.l"
return DOOR_ID;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 145 "lev_comp.l"
return DRAWBRIDGE_ID;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 146 "lev_comp.l"
return MAZEWALK_ID;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 147 "lev_comp.l"
return WALLIFY_ID;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 148 "lev_comp.l"
return REGION_ID;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 149 "lev_comp.l"
return RANDOM_OBJECTS_ID;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 150 "lev_comp.l"
return RANDOM_MONSTERS_ID;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 151 "lev_comp.l"
return RANDOM_PLACES_ID;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 152 "lev_comp.l"
return ALTAR_ID;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 153 "lev_comp.l"
return LADDER_ID;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 154 "lev_comp.l"
return STAIR_ID;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 155 "lev_comp.l"
return PORTAL_ID;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 156 "lev_comp.l"
return TELEPRT_ID;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 157 "lev_comp.l"
return RANDOMREGION_ID;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 158 "lev_comp.l"
return BRANCH_ID;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 159 "lev_comp.l"
return FOUNTAIN_ID;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 160 "lev_comp.l"
return SINK_ID;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 161 "lev_comp.l"
return POOL_ID;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 162 "lev_comp.l"
return NON_DIGGABLE_ID;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 163 "lev_comp.l"
return NON_PASSWALL_ID;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 164 "lev_comp.l"
return ROOM_ID;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 165 "lev_comp.l"
return SUBROOM_ID;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 166 "lev_comp.l"
return RAND_CORRIDOR_ID;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 167 "lev_comp.l"
return CORRIDOR_ID;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 168 "lev_comp.l"
return GOLD_ID;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 169 "lev_comp.l"
return ENGRAVING_ID;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 170 "lev_comp.l"
return NAME_ID;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 171 "lev_comp.l"
return CHANCE_ID;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 172 "lev_comp.l"
return LEV;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 173 "lev_comp.l"
{ yylval.i=D_ISOPEN; return DOOR_STATE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 174 "lev_comp.l"
{ yylval.i=D_CLOSED; return DOOR_STATE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 175 "lev_comp.l"
{ yylval.i=D_LOCKED; return DOOR_STATE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 176 "lev_comp.l"
{ yylval.i=D_NODOOR; return DOOR_STATE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 177 "lev_comp.l"
{ yylval.i=D_BROKEN; return DOOR_STATE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 178 "lev_comp.l"
{ yylval.i=W_NORTH; return DIRECTION; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 179 "lev_comp.l"
{ yylval.i=W_EAST; return DIRECTION; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 180 "lev_comp.l"
{ yylval.i=W_SOUTH; return DIRECTION; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 181 "lev_comp.l"
{ yylval.i=W_WEST; return DIRECTION; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 182 "lev_comp.l"
{ yylval.i = -1; return RANDOM_TYPE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 183 "lev_comp.l"
{ yylval.i = -2; return NONE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 184 "lev_comp.l"
return O_REGISTER;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 185 "lev_comp.l"
return M_REGISTER;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 186 "lev_comp.l"
return P_REGISTER;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 187 "lev_comp.l"
return A_REGISTER;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 188 "lev_comp.l"
return R_REGISTER;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 189 "lev_comp.l"
{ yylval.i=1; return LEFT_OR_RIGHT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 190 "lev_comp.l"
{ yylval.i=2; return LEFT_OR_RIGHT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 191 "lev_comp.l"
{ yylval.i=3; return CENTER; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 192 "lev_comp.l"
{ yylval.i=4; return LEFT_OR_RIGHT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 193 "lev_comp.l"
{ yylval.i=5; return LEFT_OR_RIGHT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 194 "lev_comp.l"
{ yylval.i=1; return TOP_OR_BOT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 195 "lev_comp.l"
{ yylval.i=5; return TOP_OR_BOT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 196 "lev_comp.l"
{ yylval.i=1; return LIGHT_STATE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 197 "lev_comp.l"
{ yylval.i=0; return LIGHT_STATE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 198 "lev_comp.l"
{ yylval.i=0; return FILLING; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 199 "lev_comp.l"
{ yylval.i=1; return FILLING; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 200 "lev_comp.l"
{ yylval.i= AM_NONE; return ALIGNMENT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 201 "lev_comp.l"
{ yylval.i= AM_LAWFUL; return ALIGNMENT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 202 "lev_comp.l"
{ yylval.i= AM_NEUTRAL; return ALIGNMENT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 203 "lev_comp.l"
{ yylval.i= AM_CHAOTIC; return ALIGNMENT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 204 "lev_comp.l"
{ yylval.i= AM_SPLEV_CO; return ALIGNMENT; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 205 "lev_comp.l"
{ yylval.i= AM_SPLEV_NONCO; return ALIGNMENT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 206 "lev_comp.l"
{ yylval.i=1; return MON_ATTITUDE; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 207 "lev_comp.l"
{ yylval.i=0; return MON_ATTITUDE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 208 "lev_comp.l"
{ yylval.i=1; return MON_ALERTNESS; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 209 "lev_comp.l"
{ yylval.i=0; return MON_ALERTNESS; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 210 "lev_comp.l"
{ yylval.i= M_AP_FURNITURE; return MON_APPEARANCE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 211 "lev_comp.l"
{ yylval.i= M_AP_MONSTER;   return MON_APPEARANCE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 212 "lev_comp.l"
{ yylval.i= M_AP_OBJECT;    return MON_APPEARANCE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 213 "lev_comp.l"
{ yylval.i=2; return ALTAR_TYPE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 214 "lev_comp.l"
{ yylval.i=1; return ALTAR_TYPE; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 215 "lev_comp.l"
{ yylval.i=0; return ALTAR_TYPE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 216 "lev_comp.l"
{ yylval.i=1; return UP_OR_DOWN; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 217 "lev_comp.l"
{ yylval.i=0; return UP_OR_DOWN; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 218 "lev_comp.l"
{ yylval.i=0; return BOOLEAN; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 219 "lev_comp.l"
{ yylval.i=1; return BOOLEAN; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 220 "lev_comp.l"
{ yylval.i=DUST; return ENGRAVING_TYPE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 221 "lev_comp.l"
{ yylval.i=ENGRAVE; return ENGRAVING_TYPE; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 222 "lev_comp.l"
{ yylval.i=BURN; return ENGRAVING_TYPE; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 223 "lev_comp.l"
{ yylval.i=MARK; return ENGRAVING_TYPE; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 224 "lev_comp.l"
{ yylval.i=ENGR_BLOOD; return ENGRAVING_TYPE; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 225 "lev_comp.l"
{ yylval.i=1; return CURSE_TYPE; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 226 "lev_comp.l"
{ yylval.i=2; return CURSE_TYPE; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 227 "lev_comp.l"
{ yylval.i=3; return CURSE_TYPE; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 228 "lev_comp.l"
{ return CONTAINED; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 229 "lev_comp.l"
{ yylval.i=OBJF_LIT; return OBJFLAG_TYPE; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 230 "lev_comp.l"
{ yylval.i=OBJF_BURIED; return OBJFLAG_TYPE; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 231 "lev_comp.l"
{ yylval.i=NOTELEPORT; return FLAG_TYPE; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 232 "lev_comp.l"
{ yylval.i=HARDFLOOR; return FLAG_TYPE; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 233 "lev_comp.l"
{ yylval.i=NOMMAP; return FLAG_TYPE; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 234 "lev_comp.l"
{ yylval.i=ARBOREAL; return FLAG_TYPE; }	/* KMH */
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 235 "lev_comp.l"
{ yylval.i=SHORTSIGHTED; return FLAG_TYPE; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 236 "lev_comp.l"
{ yylval.i=SPOOKY; return FLAG_TYPE; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 237 "lev_comp.l"
{ yylval.i=LETHE; return FLAG_TYPE; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 238 "lev_comp.l"
{ yylval.i = atoi(yytext + 1); return PERCENT; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 239 "lev_comp.l"
{ yylval.i=atoi(yytext); return INTEGER; }
	YY_BREAK
case 114:
/* rule 114 can match eol */
YY_RULE_SETUP
#line 240 "lev_comp.l"
{ yytext[yyleng-1] = 0; /* Discard the trailing \" */
		  yylval.map = (char *) alloc(strlen(yytext+1)+1);
		  Strcpy(yylval.map, yytext+1); /* Discard the first \" */
		  return STRING; }
	YY_BREAK
case 115:
/* rule 115 can match eol */
YY_RULE_SETUP
#line 244 "lev_comp.l"
{ line_number++; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 245 "lev_comp.l"
;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 246 "lev_comp.l"
{ yylval.i = yytext[2]; return CHAR; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 247 "lev_comp.l"
{ yylval.i = yytext[1]; return CHAR; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 248 "lev_comp.l"
{ return yytext[0]; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 249 "lev_comp.l"
ECHO;
	YY_BREAK
#line 1876 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MAPC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 680 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 680 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 679);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 249 "lev_comp.l"

#ifdef	AMIGA
long *alloc(n)
	unsigned n;
{
	return ((long *)malloc (n));
}
#endif

/* routine to switch to another input file; needed for flex */
void init_yyin( input_f )
FILE *input_f;
{
#if defined(FLEX_SCANNER) || defined(FLEXHACK_SCANNER)
	if (yyin)
	    yyrestart(input_f);
	else
#endif
	    yyin = input_f;
}
/* analogous routine (for completeness) */
void init_yyout( output_f )
FILE *output_f;
{
	yyout = output_f;
}

/*lev_comp.l*/

